# ReceiptGold Docker Setup
# This Docker Compose file runs all ReceiptGold services

version: '3.8'

services:
  # Backend API Server
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: receiptgold-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development  # Changed to development for better debugging
      - PORT=3000
      # Firebase config
      - EXPO_PUBLIC_FIREBASE_API_KEY=${EXPO_PUBLIC_FIREBASE_API_KEY}
      - EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN=${EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN}
      - EXPO_PUBLIC_FIREBASE_PROJECT_ID=${EXPO_PUBLIC_FIREBASE_PROJECT_ID}
      - EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET=${EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET}
      - EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      - EXPO_PUBLIC_FIREBASE_APP_ID=${EXPO_PUBLIC_FIREBASE_APP_ID}
      # Stripe config
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY=${EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY}
    volumes:
      - ./server.js:/app/server.js:ro
      - ./.env:/app/.env:ro
      - backend-node-modules:/app/node_modules
    networks:
      - receiptgold-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "com.docker.compose.project=receiptgold"
      - "service.name=Backend API"
      - "service.description=Main API server handling Stripe, Firebase, and Plaid integrations"
      - "service.url=http://localhost:3000"

  # Expo Development Server (for managed workflow - no native modules)
  expo-dev:
    build:
      context: .
      dockerfile: Dockerfile.expo
    container_name: receiptgold-expo-managed
    ports:
      - "8080:8083"
      - "19003:19000"
      - "19004:19001"
      - "19005:19002"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
      - NODE_ENV=development
      # All environment variables from .env
      - EXPO_PUBLIC_FIREBASE_API_KEY=${EXPO_PUBLIC_FIREBASE_API_KEY}
      - EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN=${EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN}
      - EXPO_PUBLIC_FIREBASE_PROJECT_ID=${EXPO_PUBLIC_FIREBASE_PROJECT_ID}
      - EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET=${EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET}
      - EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      - EXPO_PUBLIC_FIREBASE_APP_ID=${EXPO_PUBLIC_FIREBASE_APP_ID}
      - EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID=${EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID}
      - EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY=${EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      - RECEIPT_SERVICE_TYPE=${RECEIPT_SERVICE_TYPE:-ai}
      - EXPO_PUBLIC_OPENAI_API_KEY=${EXPO_PUBLIC_OPENAI_API_KEY:-}
    volumes:
      - .:/app
      # IMPORTANT: Ensure node_modules volume comes AFTER source mount
      - expo-dev-node-modules:/app/node_modules
      - expo-cache:/root/.expo
    networks:
      - receiptgold-network
    stdin_open: true
    tty: true
    restart: unless-stopped
    depends_on:
      - backend
    labels:
      - "com.docker.compose.project=receiptgold"
      - "service.name=Expo Development"
      - "service.description=React Native development server (managed workflow)"
      - "service.url=http://localhost:8080"

  # Android Development (with React Native Firebase support)
  expo-android:
    build:
      context: .
      dockerfile: Dockerfile.android
    container_name: receiptgold-android
    ports:
      - "8082:8081"
      - "19010:19000"
      - "19011:19001"
      - "19012:19002"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
      - ANDROID_HOME=/opt/android-sdk
      - ANDROID_SDK_ROOT=/opt/android-sdk
      - NODE_ENV=development
      - EAS_BUILD_PLATFORM=android
      # All environment variables from .env
      - EXPO_PUBLIC_FIREBASE_API_KEY=${EXPO_PUBLIC_FIREBASE_API_KEY}
      - EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN=${EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN}
      - EXPO_PUBLIC_FIREBASE_PROJECT_ID=${EXPO_PUBLIC_FIREBASE_PROJECT_ID}
      - EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET=${EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET}
      - EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      - EXPO_PUBLIC_FIREBASE_APP_ID=${EXPO_PUBLIC_FIREBASE_APP_ID}
      - EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID=${EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID}
      - EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY=${EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      - RECEIPT_SERVICE_TYPE=${RECEIPT_SERVICE_TYPE:-ai}
      - EXPO_PUBLIC_OPENAI_API_KEY=${EXPO_PUBLIC_OPENAI_API_KEY:-}
    volumes:
      - .:/app
      # CRITICAL: Separate node_modules for Android container to prevent conflicts
      - expo-android-node-modules:/app/node_modules
      - expo-cache:/root/.expo
      # USB device access for Android devices
      - /dev/bus/usb:/dev/bus/usb
    devices:
      # Android device access (only works on Linux hosts)
      - /dev/kvm:/dev/kvm
    privileged: true
    networks:
      - receiptgold-network
    stdin_open: true
    tty: true
    restart: unless-stopped
    depends_on:
      - backend
    profiles:
      - android
      - mobile
    labels:
      - "com.docker.compose.project=receiptgold"
      - "service.name=Android Development"
      - "service.description=Android development with React Native Firebase support"
      - "service.url=http://localhost:19010"

  # iOS Development (macOS only)
  expo-ios:
    build:
      context: .
      dockerfile: Dockerfile.ios
    container_name: receiptgold-ios
    ports:
      - "8083:8081"
      - "19020:19000"
      - "19021:19001"
      - "19022:19002"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
      - NODE_ENV=development
      - EAS_BUILD_PLATFORM=ios
      # All environment variables from .env
      - EXPO_PUBLIC_FIREBASE_API_KEY=${EXPO_PUBLIC_FIREBASE_API_KEY}
      - EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN=${EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN}
      - EXPO_PUBLIC_FIREBASE_PROJECT_ID=${EXPO_PUBLIC_FIREBASE_PROJECT_ID}
      - EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET=${EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET}
      - EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      - EXPO_PUBLIC_FIREBASE_APP_ID=${EXPO_PUBLIC_FIREBASE_APP_ID}
      - EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID=${EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID}
      - EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY=${EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      - RECEIPT_SERVICE_TYPE=${RECEIPT_SERVICE_TYPE:-ai}
      - EXPO_PUBLIC_OPENAI_API_KEY=${EXPO_PUBLIC_OPENAI_API_KEY:-}
    volumes:
      - .:/app
      # CRITICAL: Separate node_modules for iOS container
      - expo-ios-node-modules:/app/node_modules
      - expo-cache:/root/.expo
    networks:
      - receiptgold-network
    stdin_open: true
    tty: true
    restart: unless-stopped
    depends_on:
      - backend
    profiles:
      - ios
      - mobile
    labels:
      - "com.docker.compose.project=receiptgold"
      - "service.name=iOS Development"
      - "service.description=iOS development with React Native Firebase support"
      - "service.url=http://localhost:19020"

  # Nginx Reverse Proxy (for production)
  nginx:
    image: nginx:alpine
    container_name: receiptgold-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/certs:/etc/nginx/certs
    networks:
      - receiptgold-network
    depends_on:
      - backend
    restart: unless-stopped
    profiles:
      - production
    labels:
      - "com.docker.compose.project=receiptgold"
      - "service.name=Nginx Gateway"
      - "service.description=Production reverse proxy with load balancing and SSL"
      - "service.url=http://localhost"

networks:
  receiptgold-network:
    driver: bridge

volumes:
  expo-cache:
    driver: local
  # Separate node_modules volumes to prevent conflicts between containers
  expo-dev-node-modules:
    driver: local
  expo-android-node-modules:
    driver: local
  expo-ios-node-modules:
    driver: local
  backend-node-modules:
    driver: local